### ISSUE TITLE
Stuck at module initialization

### ISSUE THREAD

**Issue by joshnah** [fabnumdef/chatbot-back#39]
Hello,

I'm trying to deploy backend of the chatbot. After adding information about my database and do **npm install** and **npm run start:dev** got stuck at the the line **const app = await NestFactory.create(AppModule);** (in file **main.ts**)
as in the image below:
![image](https://user-images.githubusercontent.com/57731922/185159296-00e0cb7d-1afa-48b7-881a-3809d5ecb0f5.png)

I've never used Nestjs before and I'm new to backend, did I miss any steps?

Thanks a lot!

**Comment by vincentlaine** [comment]
Hi, 

Check if you are in Node version 14 or 16.
If it is okay try to remove the node_modules package and reinstall it.

This bug occurs sometimes with NestJS.

**Comment by joshnah** [comment]
> Hi,
> 
> Check if you are in Node version 14 or 16. If it is okay try to remove the node_modules folder and reinstall it.
> 
> This bug occurs sometimes with NestJS.

Hi,

I tried to reinstall node version 14 and 16 and the issue still occurs. Is there any other workarounds that I can try? Thanks

**Comment by vincentlaine** [comment]
Hi I did not have the bug because I use yarn and not npm.

Try re-installing the project using yarn install + yarn start:dev.
